# Generated by Django 4.2.16 on 2024-11-24 01:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=40)),
                ('quantity', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('units', models.CharField(default='items', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('average_rating', models.FloatField(default=0.0)),
                ('creation_time', models.DateTimeField()),
                ('steps', models.TextField()),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(default='', max_length=10000)),
                ('list_ingredient', models.ManyToManyField(blank=True, to='homey.ingredientitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')])),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='homey.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('user_since', models.DateTimeField()),
                ('bookmarked_recipes', models.ManyToManyField(to='homey.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('quantity', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('units', models.CharField(default='items', max_length=40)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grocery_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('temp_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('location', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('attendees', models.CharField(blank=True, max_length=30)),
                ('eventlink', models.CharField(default='https://calendar.google.com', max_length=30)),
                ('eventType', models.CharField(default='default', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
